spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mini_blog_db
    username: dev_user
    password: ${DB_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6380
  jpa:
    show-sql: true
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000
logging:
  level:
    com.margaretnjoki.miniblog: DEBUG
    org.hibernate.SQL: DEBUG