spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}

  jpa:
    show-sql: false

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000
server:
  port: ${PORT:8080}

logging:
  level:
    com.margaretnjoki.miniblog: INFO
    root: WARN