spring:
  application:
    name: mini-blog-api

  datasource:
    url: jdbc:postgresql://localhost:5432/mini_blog_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:mQ7vL9nP4xX2wR8kZ5aT3cF1hJ6sN0dE9yU2gV7bK4pR8wX1zC5nM6qH3tF9aL2s}
  expiration-ms: 3600000

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO