spring:
  application:
    name: mini-blog-api

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO